/*
* This class will handle all user interactions,
* such as displaying prompts for the user to input
* their phone number and displaying the list of potential
* words generated by the program.
*
* */

public class UI {

}
